FROM gradle:6.2.0-jdk8 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build --no-daemon

FROM java:8
EXPOSE 8080
COPY --from=build /home/gradle/src/build/libs/mongo-pdf-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","app.war"]